export enum ImprovementStatus {
  QUEUED = 'QUEUED',
  CLONING = 'CLONING',
  GENERATING = 'GENERATING',
  TESTING = 'TESTING',
  PUSHING = 'PUSHING',
  CREATING_PR = 'CREATING_PR',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
