export enum ScanStatus {
  NOT_STARTED = 'NOT_STARTED',
  CLONING = 'CLONING',
  SCANNING = 'SCANNING',
  INSTALLING = 'INSTALLING',
  TESTING = 'TESTING',
  COMPLETE = 'COMPLETE',
  FAILED = 'FAILED',
}
